name: biblioteca
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  pdf: ^3.10.7
  printing: ^5.11.1
  cloud_firestore: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/juegodetronos.jpg
    - assets/images/ladamadelascamelias.jpg
    - assets/images/alasdesangre.jpg
    - assets/images/elpadrino.jpg
    - assets/images/harrypotter.jpg
    - assets/images/orgulloyprejuicio.jpg
    - assets/images/elfantasmadelaopera.jpg
    - assets/images/dune.jpg
    - assets/logo.jpg
